### ISSUE TITLE
Vampires are unable to respawn

### ISSUE THREAD

**Issue by Alkiasan** [williambl/haema#117] opened 2022-03-06 20:51 UTC
This gets spammed in logs whenever they attempt to respawn:
https://www.toptal.com/developers/hastebin/nukowuceje.yaml

**Comment by williambl** [comment] 2022-04-02 17:23
would you mind re-uploading the log? it's been deleted.

**Comment by Alkiasan** [comment] 2022-04-02 18:33
Weirdly enough, I can't reproduce an error. Now, when a player dies, they can respawn in the same exact position they died in. Their playermodel will be stuck in the dying state, but apart from that the rest would be normal.
If i recall correctly the error was relating to being unable to find a suitable spawn location on the surface, although I cannot find it since it's been so long since I reported this.

**Comment by williambl** [comment] 2022-04-02 18:56
Yeah, that happens sometimes. Still not quite sure what the cause is. I'm gonna close this as a duplicate of #106.

**Closed as completed by williambl** 2022-04-02 18:56 UTC
Labels: duplicate
