### ISSUE TITLE
Critical injection failure caused by "allowVampiresToSleepInDay" crashes game before start up

### ISSUE THREAD

**Issue by Tankuu** [williambl/haema#32] opened 2021-02-15 03:35 UTC
My game will no longer start. I am using a custom 1.16.5 modpack with Haema version 1.5.1

All I have done is:

- Removed "Terrestria"
- Removed "Traverse"
- Added "Oh The Biomes You'll Go [Fabric]"
- Added "Biome Picker"
- Added "Comforts (Fabric)"
- Added "Greater Eye of Ender [FABRIC]"
- Added "Powershot"

This modpack worked perfectly up until now :(

**Crash log:** https://pastebin.com/i8wuRTTS

**EDIT:** I will be looking into this for a bit as well while I try to solve the problem. I did not thoroughly go through the log, but seeing as there was a possible error with Haema I decided to create an issue for it.

**Comment by Tankuu** [comment] 2021-02-15 05:17
Just saw this was supposedly a duplicate of #31 and #21. However, I do not have Somnus as far as I am aware of.

**Comment by williambl** [comment] 2021-02-15 11:21
Somnus is included in the Comforts mod.

Marking as duplicate of #21.

**Closed** 2021-02-15 11:21 UTC

**Comment by williambl** [comment] 2021-02-15 22:22
Fixed in 1.5.2.
