### ISSUE TITLE
Keep getting text "errors with currently selected data packs prevented world from loading"

### ISSUE THREAD

**Issue by beautiful-lunatic** [williambl/haema#68] opened 2021-06-23 17:48 UTC
Keep getting this message even though I don't have or use datapacks.

**Comment by MoZarka** [comment] 2021-06-23 19:13
yep, same. exclusively this mods problem

**Comment by williambl** [comment] 2021-06-24 14:30
Please give a log.

**Comment by williambl** [comment] 2021-06-24 23:22
I've been informed this only happens with Adorn installed, can this be confirmed?

**Comment by beautiful-lunatic** [comment] 2021-06-25 11:02
> I've been informed this only happens with Adorn installed, can this be confirmed?

Sorry I never got back to you earlier, I believe it was Adorn since I have that installed. I did get it to run, but for some reason the Vampire Hunter Pillagers were a little bugged. Their bodies weren't fully rendered or loaded, so they were just floating heads and arms that didn't make any noise

**Comment by williambl** [comment] 2021-06-26 19:21
Actually this seems to be an issue with LibCD.

**Comment by williambl** [comment] 2021-06-26 19:22
> Vampire Hunter Pillagers were a little bugged

Known issue, will be fixed.

**Comment by williambl** [comment] 2021-06-27 19:00
Should to be fixed in 1.7.2?

**Closed by williambl** 2021-06-27 19:00 UTC
